name: Deploy react app

on:
  push:
    branches:
      - develop

jobs:
  deploy:
    name: deploy app
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [ "16.x" ]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: ${{matrix.node-version}}
      - name: install packages
        run: npm install
      - name: deploy the app
        run: |
          git config --global user.name 'XxLuisFer15xX'
          git config --global user.email 'luisfer.sm15@gmail.com'
          git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}
          npm run deploy
